# Generated by Django 5.0.3 on 2024-03-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anilist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_romaji', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('banner_image', models.URLField()),
                ('cover_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AnilistUser',
            fields=[
                ('anilist_userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('associated_emoji', models.CharField(max_length=8)),
                ('anime', models.ManyToManyField(to='aniwheel.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shown_anime', models.ManyToManyField(to='aniwheel.anime')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedAnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.anime')),
                ('watched_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.session')),
            ],
        ),
    ]
