# Generated by Django 5.0.3 on 2024-03-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('associated_emoji', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anilist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_romaji', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(max_length=255)),
                ('banner_image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnilistUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aniwheel.user')),
                ('anilist_userid', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.URLField(null=True)),
                ('anime', models.ManyToManyField(to='aniwheel.anime')),
            ],
            bases=('aniwheel.user',),
        ),
        migrations.CreateModel(
            name='WatchedAnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.anime')),
                ('watched_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.session')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.anilistuser')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='shown_anime',
            field=models.ManyToManyField(through='aniwheel.WatchedAnimeStatus', to='aniwheel.anime'),
        ),
        migrations.CreateModel(
            name='WheelAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.anime')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.wheel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.anilistuser')),
            ],
        ),
        migrations.AddField(
            model_name='wheel',
            name='anime',
            field=models.ManyToManyField(through='aniwheel.WheelAnime', to='aniwheel.anime'),
        ),
    ]
