# Generated by Django 5.0.3 on 2024-03-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedanimestatus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.user'),
        ),
        migrations.AlterField(
            model_name='wheelanime',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniwheel.user'),
        ),
    ]
