# Generated by Django 5.0.3 on 2024-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover_color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchedanimestatus',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
