# Generated by Django 5.0.3 on 2024-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0002_anime_cover_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_romaji',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
