# Generated by Django 5.0.3 on 2024-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0003_alter_anime_title_en_alter_anime_title_romaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anilistuser',
            name='associated_emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='anilistuser',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='banner_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='cover_image',
            field=models.URLField(null=True),
        ),
    ]
