# Generated by Django 5.0.3 on 2024-03-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0004_alter_anilistuser_associated_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_romaji',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
