# Generated by Django 5.0.3 on 2024-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0005_alter_anime_title_en_alter_anime_title_romaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
