# Generated by Django 5.0.3 on 2024-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniwheel', '0006_alter_anime_cover_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
